"""create students table

Revision ID: 08947c46b9c2
Revises: 
Create Date: 2026-05-16 17:48:08.124969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08947c46b9c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Фамилия', sa.String(length=100), nullable=False),
    sa.Column('Имя', sa.String(length=100), nullable=False),
    sa.Column('Факультет', sa.String(length=50), nullable=False),
    sa.Column('Курс', sa.String(length=100), nullable=False),
    sa.Column('Оценка', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_Фамилия'), 'students', ['Фамилия'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_Фамилия'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
